# Generated by Django 3.1.5 on 2021-01-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210122_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Beleivered', 'Belivered'), ('Not Belivered', 'Not bdelivered')], default='In products', max_length=20),
        ),
    ]
