# Generated by Django 3.1.5 on 2021-01-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210122_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='default_product_image.png', null=True, upload_to=''),
        ),
    ]
