# Generated by Django 3.1.5 on 2021-01-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210122_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='default_product_image.jpg', null=True, upload_to=''),
        ),
    ]
