# Generated by Django 3.1.5 on 2021-01-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210127_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_us',
            new_name='Aboutus',
        ),
    ]
