# Generated by Django 3.1.5 on 2021-01-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_contancts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contancts',
            new_name='Cotancts',
        ),
    ]
