# Generated by Django 3.1.5 on 2021-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20210128_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotancts',
            name='last_name_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cotancts',
            name='name_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
