# Generated by Django 3.1.5 on 2021-01-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210128_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotancts',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
