# Generated by Django 3.1.5 on 2021-01-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210128_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotancts',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
