# Generated by Django 3.1.5 on 2021-01-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_cotancts_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotancts',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
