# Generated by Django 3.1.5 on 2021-01-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210128_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotancts',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotancts',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
