# Generated by Django 3.1.5 on 2021-01-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20210128_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotancts',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='cotancts',
            name='lon',
        ),
        migrations.AddField(
            model_name='cotancts',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotancts',
            name='longtitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotancts',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cotancts',
            name='last_name_user',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cotancts',
            name='name_user',
            field=models.CharField(max_length=20),
        ),
    ]
