# Generated by Django 3.1.5 on 2021-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210129_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotancts',
            name='contacttype',
            field=models.CharField(choices=[('phone', 'phone'), ('email', 'email'), ('address', 'address')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotancts',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
