# Generated by Django 3.1.5 on 2021-01-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210129_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotancts',
            old_name='contacttype',
            new_name='contact_type',
        ),
    ]
