# Generated by Django 3.1.5 on 2021-02-05 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0026_progile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progile',
            new_name='Profile',
        ),
    ]
