# Generated by Django 3.1.5 on 2021-02-09 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210205_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.date(2021, 2, 9)),
        ),
    ]
