# Generated by Django 3.1.5 on 2021-02-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210209_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.BooleanField(default=True),
        ),
    ]
