# Generated by Django 3.1.5 on 2021-02-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210209_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
