# Generated by Django 3.1.5 on 2021-02-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210212_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
