# Generated by Django 3.1.5 on 2021-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_profile_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('money', 'money'), ('wallet', 'wallet')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
