# Generated by Django 3.1.5 on 2021-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sale_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
