# Generated by Django 3.1.5 on 2021-02-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_profile_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sale_amount',
            field=models.FloatField(default=0.1),
        ),
    ]
