# Generated by Django 3.1.5 on 2021-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210212_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sale_amount',
            field=models.FloatField(default=0.01),
        ),
    ]
